# Generated by Django 3.2.25 on 2025-09-26 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitydata',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='activitydata',
            unique_together={('user', 'date')},
        ),
        migrations.CreateModel(
            name='WeightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SleepData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bedtime', models.DateTimeField(blank=True, null=True)),
                ('sleep_start', models.DateTimeField(blank=True, null=True)),
                ('sleep_end', models.DateTimeField(blank=True, null=True)),
                ('wake_time', models.DateTimeField(blank=True, null=True)),
                ('total_sleep_minutes', models.IntegerField(default=0)),
                ('deep_sleep_minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('light_sleep_minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('rem_sleep_minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('awake_minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('sleep_quality_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
