version: '3.8'
services:
  web:
    build:
      context: ../ 
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../fitfolio:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres
    environment:
      POSTGRES_DB: fitfolio
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  redis:
    image: redis
  celery:
    build:
      context: ../ 
      dockerfile: docker/Dockerfile
    command: celery -A fitfolio worker -l info
    depends_on:
      - web
      - redis