version: '3.8'
services:
  web:
    build:
      context: ../ 
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../fitfolio:/usr/src/app
    ports:
       - "$FITFOLIO_PORT:8000"
    depends_on:
      - mariadb
      - redis
  mariadb:
    container_name: fitfolio_db
    image: mariadb:latest
    volumes:
      - $DOCKERDIR/appdata/fitfolio_db/config:/config
      - $DOCKERDIR/appdata/fitfolio_db/mysql:/var/lib/mysql
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      MARIADB_DATABASE: $MARIADB_DATABASE
      MARIADB_PASSWORD: $MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_USER: $MARIADB_USER
  redis:
    image: redis:latest
    container_name: fitfolio_redis
    ports:
       - "$REDIS_PORT:6379"
    volumes:
      - $DOCKERDIR/appdata/fitfolio_redis/data:/var/lib/redis
      - $DOCKERDIR/appdata/fitfolio_redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /etc/localtime:/etc/localtime:ro  
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      REDIS_PASSWORD: $REDIS_PASSWORD
  celery:
    build:
      context: ../ 
      dockerfile: docker/Dockerfile
    command: celery -A fitfolio worker -l info
    depends_on:
      - web
      - redis
