version: '3.8'
services:
  web:
    build:
      context: ../ 
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../fitfolio:/usr/src/app
    ports:
       - "${FITFOLIO_PORT:-8000}:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3
      - HCGATEWAY_API_URL=${HCGATEWAY_API_URL:-https://api.hcgateway.shuchir.dev}

  db:
    image: postgres:13
    container_name: fitfolio_db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fitfolio}
      POSTGRES_USER: ${POSTGRES_USER:-fitfolio}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fitfolio123}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  redis:
    image: redis:alpine
    container_name: fitfolio_redis
    volumes:
      - redis_data:/data
    ports:
       - "${REDIS_PORT:-6379}:6379"

  celery:
    build:
      context: ../ 
      dockerfile: docker/Dockerfile
    command: celery -A fitfolio worker -l info
    volumes:
      - ../fitfolio:/usr/src/app
    depends_on:
      - web
      - redis
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3
      - HCGATEWAY_API_URL=${HCGATEWAY_API_URL:-https://api.hcgateway.shuchir.dev}

  celery-beat:
    build:
      context: ../ 
      dockerfile: docker/Dockerfile
    command: celery -A fitfolio beat -l info
    volumes:
      - ../fitfolio:/usr/src/app
    depends_on:
      - web
      - redis
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3
      - HCGATEWAY_API_URL=${HCGATEWAY_API_URL:-https://api.hcgateway.shunchir.dev}

  health-sync:
    build:
      context: ../ 
      dockerfile: docker/Dockerfile
    command: >
      sh -c "
        while true; do
          echo 'Running health data sync...'
          python manage.py sync_health_data --all
          echo 'Health sync completed. Sleeping for 2 hours...'
          sleep 7200
        done
      "
    volumes:
      - ../fitfolio:/usr/src/app
    depends_on:
      - web
      - db
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3
      - HCGATEWAY_API_URL=${HCGATEWAY_API_URL:-https://api.hcgateway.shuchir.dev}
    restart: unless-stopped

volumes:
  db_data:
  redis_data:
